name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Copy deploy script and execute
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 28
          script: |
            chmod +x /usr/local/lsws/quanly.pilates.net.vn/html/deploy.sh
            /usr/local/lsws/quanly.pilates.net.vn/html/deploy.sh 